name: Generate report

on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 15,23 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: sudo apt-get install python3-setuptools
        run: sudo apt-get install python3-setuptools
      
      - name: pip3 install pandas && pip3 install matplotlib && pip3 install seaborn
        run: pip3 install pandas && pip3 install matplotlib && pip3 install seaborn

      - name: Get GitHub Commit Data
        run: python3 get_github_commit_data.py

      - name: Get Phabricator Diff Data
        env:
          PHABRICATOR_API_TOKEN: ${{secrets.PHABRICATOR_API_TOKEN}}
        run: python3 get_phabricator_diff_data.py

      - name: Generate CSV
        run: python3 generate_table.py
        
      - name: Generate boxplot
        run: python3 generate_plots.py
        
      - name: Configure Git
        run: |
            git config user.name 'runner'
            git config user.email 'runner@github.com'
            
      - name: git add table.csv && git add boxplot.svg
        run: git add table.csv && git add boxplot.svg
        
      - name: git commit -m "$(date)"
        run: git commit -m "$(date)" || echo "No changes to table or plots"
      
      - name: git push
        run: git push
